# Stage 1: Build the Angular app
FROM node:latest AS build

# Set working directory
WORKDIR /app

COPY . .

# Install Angular CLI and dependencies
RUN npm install

# Build the Angular app for production
RUN npm run build

# Stage 2: Set up Nginx to serve the built app
FROM nginx:alpine

# Copy the built app from the build stage to Nginx's default directory
COPY --from=build /app/dist/AstrologyApp /usr/share/nginx/html

# Expose the port Nginx will listen on
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
